#pragma once
#include "GameConstants.h"

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;
	Image* ResoddedFrameworkLoadImageById(ResourceManager *theManager, int theId);	void ResoddedFrameworkReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ResoddedFrameworkExtractResourcesByName(ResourceManager *theManager, const char *theName);
	bool ResoddedFrameworkExtractLoaderBarResources(ResourceManager *theMgr);

	// LoadingImages Resources
	bool ResoddedFrameworkExtractLoadingImagesResources(ResourceManager *theMgr);
	extern Image* IMAGE_SEED_SELECTOR;
	extern Image* IMAGE_GAMEPAD_CURSOR_FRAME;
	extern Image* IMAGE_GAMEPAD_CURSOR_ARROWS;
	extern Image* IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW;
	extern Image* IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW;

	// Widescreen Resources
#if LAWN_WIDESCREEN
	extern Image* IMAGE_TITLESCREEN_WIDESCREEN;
	extern Image* IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN;
	extern Image* IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN;
	extern Image* IMAGE_STORE_BACKGROUND_WIDESCREEN;
	extern Image* IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND1_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND2_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND3_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND4_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND5_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND6_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN;
	extern Image* IMAGE_AQUARIUM1_WIDESCREEN;
	extern Image* IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN;
	extern Image* IMAGE_ALMANAC_INDEXBACK_WIDESCREEN;
	extern Image* IMAGE_ALMANAC_PLANTBACK_WIDESCREEN;
	extern Image* IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN;
	extern Image* IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN;
	extern Image* IMAGE_REANIM_TREE_BG_WIDESCREEN;
	extern Image* IMAGE_BACKGROUND1_COVER;
	extern Image* IMAGE_BACKGROUND2_COVER;
	extern Image* IMAGE_BACKGROUND3_COVER;
	extern Image* IMAGE_BACKGROUND4_COVER;
	extern Image* IMAGE_BACKGROUND5_TREES;
	extern Image* IMAGE_BACKGROUND5_POLE;
	extern Image* IMAGE_BACKGROUND6_TREES;
	extern Image* IMAGE_BACKGROUND6_POLE;
#endif

	enum ResoddedFrameworkResourceId
	{
		IMAGE_SEED_SELECTOR_ID,
		IMAGE_GAMEPAD_CURSOR_FRAME_ID,
		IMAGE_GAMEPAD_CURSOR_ARROWS_ID,
		IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW_ID,
		IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW_ID,
#if LAWN_WIDESCREEN
		IMAGE_TITLESCREEN_WIDESCREEN_ID,
		IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN_ID,
		IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN_ID,
		IMAGE_STORE_BACKGROUND_WIDESCREEN_ID,
		IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN_ID,
		IMAGE_BACKGROUND1_WIDESCREEN_ID,
		IMAGE_BACKGROUND2_WIDESCREEN_ID,
		IMAGE_BACKGROUND3_WIDESCREEN_ID,
		IMAGE_BACKGROUND4_WIDESCREEN_ID,
		IMAGE_BACKGROUND5_WIDESCREEN_ID,
		IMAGE_BACKGROUND6_WIDESCREEN_ID,
		IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN_ID,
		IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN_ID,
		IMAGE_AQUARIUM1_WIDESCREEN_ID,
		IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN_ID,
		IMAGE_ALMANAC_INDEXBACK_WIDESCREEN_ID,
		IMAGE_ALMANAC_PLANTBACK_WIDESCREEN_ID,
		IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN_ID,
		IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN_ID,
		IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN_ID,
		IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN_ID,
		IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN_ID,
		IMAGE_REANIM_TREE_BG_WIDESCREEN_ID,
		IMAGE_BACKGROUND1_COVER_ID,
		IMAGE_BACKGROUND2_COVER_ID,
		IMAGE_BACKGROUND3_COVER_ID,
		IMAGE_BACKGROUND4_COVER_ID,
		IMAGE_BACKGROUND5_TREES_ID,
		IMAGE_BACKGROUND5_POLE_ID,
		IMAGE_BACKGROUND6_TREES_ID,
		IMAGE_BACKGROUND6_POLE_ID,
#endif
		ResoddedFrameworkRESOURCE_ID_MAX
	};

	Image* ResoddedFrameworkGetImageById(int theId);
	Font* ResoddedFrameworkGetFontById(int theId);
	int ResoddedFrameworkGetSoundById(int theId);

	Image*& ResoddedFrameworkGetImageRefById(int theId);
	Font*& ResoddedFrameworkGetFontRefById(int theId);
	int& ResoddedFrameworkGetSoundRefById(int theId);

	ResoddedFrameworkResourceId ResoddedFrameworkGetIdByImage(Image *theImage);
	ResoddedFrameworkResourceId ResoddedFrameworkGetIdByFont(Font *theFont);
	ResoddedFrameworkResourceId ResoddedFrameworkGetIdBySound(int theSound);

	const char* ResoddedFrameworkGetStringIdById(int theId);
	ResoddedFrameworkResourceId ResoddedFrameworkGetIdByStringId(const char *theStringId);

} // namespace Sexy

