#include "FrameworkResources.h"
#include "Sexy.TodLib/TodCommon.h"
#include "SexyAppFramework/ResourceManager.h"
using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ResoddedFrameworkExtractResourcesByName(ResourceManager * theManager, const char* theName)
{
	if (strcmp(theName,"LoadingImages")==0) return ResoddedFrameworkExtractLoadingImagesResources(theManager);
	if (strcmp(theName,"LoaderBar")==0) return ResoddedFrameworkExtractLoaderBarResources(theManager);
	return false;
}

Sexy::ResoddedFrameworkResourceId Sexy::ResoddedFrameworkGetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<ResoddedFrameworkRESOURCE_ID_MAX; i++)
			aMap[ResoddedFrameworkGetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return ResoddedFrameworkRESOURCE_ID_MAX;
	else
		return (ResoddedFrameworkResourceId) anItr->second;
}

// LoadingImages Resources
Image* Sexy::IMAGE_SEED_SELECTOR;
Image* Sexy::IMAGE_GAMEPAD_CURSOR_FRAME;
Image* Sexy::IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW;
Image* Sexy::IMAGE_GAMEPAD_SELECTOR_SHADOW;
Image* Sexy::IMAGE_GAMEPAD_ARROW;
Image *Sexy::IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW;

// Widescreen Resources
#if LAWN_WIDESCREEN
Image* Sexy::IMAGE_TITLESCREEN_WIDESCREEN;
Image* Sexy::IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN;
Image* Sexy::IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN;
Image* Sexy::IMAGE_STORE_BACKGROUND_WIDESCREEN;
Image* Sexy::IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN;
Image* Sexy::IMAGE_STORE_CAR_WIDESCREEN;
Image* Sexy::IMAGE_STORE_CAR_NIGHT_WIDESCREEN;
Image* Sexy::IMAGE_STORE_CARCLOSED_WIDESCREEN;
Image* Sexy::IMAGE_STORE_CARCLOSED_NIGHT_WIDESCREEN;
Image* Sexy::IMAGE_STORE_HATCHBACKOPEN_WIDESCREEN;
Image* Sexy::IMAGE_STORE_SIGN_WIDESCREEN;
Image* Sexy::IMAGE_STORE_MAINMENUBUTTON_WIDESCREEN;
Image* Sexy::IMAGE_STORE_MAINMENUBUTTONDOWN_WIDESCREEN;
Image* Sexy::IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_WIDESCREEN;
Image* Sexy::IMAGE_STORE_PREVBUTTON_WIDESCREEN;
Image* Sexy::IMAGE_STORE_PREVBUTTONHIGHLIGHT_WIDESCREEN;
Image* Sexy::IMAGE_STORE_PREVBUTTONDISABLED_WIDESCREEN;
Image* Sexy::IMAGE_STORE_NEXTBUTTON_WIDESCREEN;
Image* Sexy::IMAGE_STORE_NEXTBUTTONHIGHLIGHT_WIDESCREEN;
Image* Sexy::IMAGE_STORE_NEXTBUTTONDISABLED_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND1_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND2_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND3_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND4_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND5_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND6_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN;
Image* Sexy::IMAGE_AQUARIUM1_WIDESCREEN;
Image* Sexy::IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN;
Image* Sexy::IMAGE_ALMANAC_INDEXBACK_WIDESCREEN;
Image* Sexy::IMAGE_ALMANAC_PLANTBACK_WIDESCREEN;
Image* Sexy::IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN;
Image* Sexy::IMAGE_ZOMBATAR_BG_WIDESCREEN;
Image* Sexy::IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN;
Image* Sexy::IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN;
Image* Sexy::IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN;
Image* Sexy::IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN;
Image* Sexy::IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN;
Image* Sexy::IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN;
Image* Sexy::IMAGE_REANIM_TREE_BG_WIDESCREEN;
Image* Sexy::IMAGE_BACKGROUND1_COVER;
Image* Sexy::IMAGE_BACKGROUND2_COVER;
Image* Sexy::IMAGE_BACKGROUND3_COVER;
Image* Sexy::IMAGE_BACKGROUND4_COVER;
Image* Sexy::IMAGE_BACKGROUND5_TREES;
Image* Sexy::IMAGE_BACKGROUND5_POLE;
Image* Sexy::IMAGE_BACKGROUND6_TREES;
Image* Sexy::IMAGE_BACKGROUND6_POLE;
#endif

bool Sexy::ResoddedFrameworkExtractLoaderBarResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;

	auto safeGetImage = [&aMgr](Image*& theImagePtr, const std::string& theId) {
		try { theImagePtr = aMgr.GetImageThrow(theId); }
		catch(ResourceManagerException&) {}
	};

#if LAWN_WIDESCREEN
	safeGetImage(IMAGE_TITLESCREEN_WIDESCREEN, "IMAGE_TITLESCREEN_WIDESCREEN");
#endif

	return true;
}

bool Sexy::ResoddedFrameworkExtractLoadingImagesResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;

	auto safeGetImage = [&aMgr](Image*& theImagePtr, const std::string& theId) {
		try { theImagePtr = aMgr.GetImageThrow(theId); }
		catch(ResourceManagerException&) {}
	};

	safeGetImage(IMAGE_SEED_SELECTOR, "IMAGE_SEED_SELECTOR");
	safeGetImage(IMAGE_GAMEPAD_CURSOR_FRAME, "IMAGE_GAMEPAD_CURSOR_FRAME");
	safeGetImage(IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW, "IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW");
	safeGetImage(IMAGE_GAMEPAD_SELECTOR_SHADOW, "IMAGE_GAMEPAD_SELECTOR_SHADOW");
	safeGetImage(IMAGE_GAMEPAD_ARROW, "IMAGE_GAMEPAD_ARROW");
	safeGetImage(IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW, "IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW");
#if LAWN_WIDESCREEN
	safeGetImage(IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN, "IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN");
	safeGetImage(IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN, "IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN");
	safeGetImage(IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN, "IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN");
	safeGetImage(IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN, "IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN");
	safeGetImage(IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN, "IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN");
	safeGetImage(IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN, "IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN");
	safeGetImage(IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN, "IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN");
	safeGetImage(IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN, "IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN");
	if (IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN)
		TodMarkImageForSanding(IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN);
	if (IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN)
		TodMarkImageForSanding(IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN);
	safeGetImage(IMAGE_STORE_BACKGROUND_WIDESCREEN, "IMAGE_STORE_BACKGROUND_WIDESCREEN");
	safeGetImage(IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN, "IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN");
	safeGetImage(IMAGE_STORE_CAR_WIDESCREEN, "IMAGE_STORE_CAR_WIDESCREEN");
	safeGetImage(IMAGE_STORE_CAR_NIGHT_WIDESCREEN, "IMAGE_STORE_CAR_NIGHT_WIDESCREEN");
	safeGetImage(IMAGE_STORE_CARCLOSED_WIDESCREEN, "IMAGE_STORE_CARCLOSED_WIDESCREEN");
	safeGetImage(IMAGE_STORE_CARCLOSED_NIGHT_WIDESCREEN, "IMAGE_STORE_CARCLOSED_NIGHT_WIDESCREEN");
	safeGetImage(IMAGE_STORE_HATCHBACKOPEN_WIDESCREEN, "IMAGE_STORE_HATCHBACKOPEN_WIDESCREEN");
	safeGetImage(IMAGE_STORE_SIGN_WIDESCREEN, "IMAGE_STORE_SIGN_WIDESCREEN");
	safeGetImage(IMAGE_STORE_MAINMENUBUTTON_WIDESCREEN, "IMAGE_STORE_MAINMENUBUTTON_WIDESCREEN");
	safeGetImage(IMAGE_STORE_MAINMENUBUTTONDOWN_WIDESCREEN, "IMAGE_STORE_MAINMENUBUTTONDOWN_WIDESCREEN");
	safeGetImage(IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_WIDESCREEN, "IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_WIDESCREEN");
	safeGetImage(IMAGE_STORE_PREVBUTTON_WIDESCREEN, "IMAGE_STORE_PREVBUTTON_WIDESCREEN");
	safeGetImage(IMAGE_STORE_PREVBUTTONHIGHLIGHT_WIDESCREEN, "IMAGE_STORE_PREVBUTTONHIGHLIGHT_WIDESCREEN");
	safeGetImage(IMAGE_STORE_PREVBUTTONDISABLED_WIDESCREEN, "IMAGE_STORE_PREVBUTTONDISABLED_WIDESCREEN");
	safeGetImage(IMAGE_STORE_NEXTBUTTON_WIDESCREEN, "IMAGE_STORE_NEXTBUTTON_WIDESCREEN");
	safeGetImage(IMAGE_STORE_NEXTBUTTONHIGHLIGHT_WIDESCREEN, "IMAGE_STORE_NEXTBUTTONHIGHLIGHT_WIDESCREEN");
	safeGetImage(IMAGE_STORE_NEXTBUTTONDISABLED_WIDESCREEN, "IMAGE_STORE_NEXTBUTTONDISABLED_WIDESCREEN");
	// IMAGE_ZOMBATAR_BG_WIDESCREEN is delay-loaded with Zombatar resources

	safeGetImage(IMAGE_BACKGROUND1_WIDESCREEN, "IMAGE_BACKGROUND1_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND2_WIDESCREEN, "IMAGE_BACKGROUND2_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND3_WIDESCREEN, "IMAGE_BACKGROUND3_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND4_WIDESCREEN, "IMAGE_BACKGROUND4_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND5_WIDESCREEN, "IMAGE_BACKGROUND5_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND6_WIDESCREEN, "IMAGE_BACKGROUND6_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN, "IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN, "IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN");
	safeGetImage(IMAGE_AQUARIUM1_WIDESCREEN, "IMAGE_BACKGROUND_ZOMBIQUARIUM_WIDESCREEN");
	safeGetImage(IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN, "IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN");
	safeGetImage(IMAGE_ALMANAC_INDEXBACK_WIDESCREEN, "IMAGE_ALMANAC_INDEXBACK_WIDESCREEN");
	safeGetImage(IMAGE_ALMANAC_PLANTBACK_WIDESCREEN, "IMAGE_ALMANAC_PLANTBACK_WIDESCREEN");
	safeGetImage(IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN, "IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN");
	safeGetImage(IMAGE_REANIM_TREE_BG_WIDESCREEN, "IMAGE_REANIM_TREE_BG_WIDESCREEN");
	safeGetImage(IMAGE_BACKGROUND1_COVER, "IMAGE_BACKGROUND1_COVER");
	safeGetImage(IMAGE_BACKGROUND2_COVER, "IMAGE_BACKGROUND2_COVER");
	safeGetImage(IMAGE_BACKGROUND3_COVER, "IMAGE_BACKGROUND3_COVER");
	safeGetImage(IMAGE_BACKGROUND4_COVER, "IMAGE_BACKGROUND4_COVER");
	safeGetImage(IMAGE_BACKGROUND5_TREES, "IMAGE_BACKGROUND5_TREES");
	safeGetImage(IMAGE_BACKGROUND5_POLE, "IMAGE_BACKGROUND5_POLE");
	safeGetImage(IMAGE_BACKGROUND6_TREES, "IMAGE_BACKGROUND6_TREES");
	safeGetImage(IMAGE_BACKGROUND6_POLE, "IMAGE_BACKGROUND6_POLE");
#endif

	return true;
}

static void* gResources[] =
{
	&IMAGE_SEED_SELECTOR,
	&IMAGE_GAMEPAD_CURSOR_FRAME,
	&IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW,
	&IMAGE_GAMEPAD_SELECTOR_SHADOW,
	&IMAGE_GAMEPAD_ARROW,
	&IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW,
#if LAWN_WIDESCREEN
	&IMAGE_TITLESCREEN_WIDESCREEN,
	&IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN,
	&IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN,
	&IMAGE_STORE_BACKGROUND_WIDESCREEN,
	&IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN,
	&IMAGE_STORE_CAR_WIDESCREEN,
	&IMAGE_STORE_CAR_NIGHT_WIDESCREEN,
	&IMAGE_STORE_CARCLOSED_WIDESCREEN,
	&IMAGE_STORE_CARCLOSED_NIGHT_WIDESCREEN,
	&IMAGE_STORE_HATCHBACKOPEN_WIDESCREEN,
	&IMAGE_STORE_SIGN_WIDESCREEN,
	&IMAGE_STORE_MAINMENUBUTTON_WIDESCREEN,
	&IMAGE_STORE_MAINMENUBUTTONDOWN_WIDESCREEN,
	&IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_WIDESCREEN,
	&IMAGE_STORE_PREVBUTTON_WIDESCREEN,
	&IMAGE_STORE_PREVBUTTONHIGHLIGHT_WIDESCREEN,
	&IMAGE_STORE_PREVBUTTONDISABLED_WIDESCREEN,
	&IMAGE_STORE_NEXTBUTTON_WIDESCREEN,
	&IMAGE_STORE_NEXTBUTTONHIGHLIGHT_WIDESCREEN,
	&IMAGE_STORE_NEXTBUTTONDISABLED_WIDESCREEN,
	&IMAGE_BACKGROUND1_WIDESCREEN,
	&IMAGE_BACKGROUND2_WIDESCREEN,
	&IMAGE_BACKGROUND3_WIDESCREEN,
	&IMAGE_BACKGROUND4_WIDESCREEN,
	&IMAGE_BACKGROUND5_WIDESCREEN,
	&IMAGE_BACKGROUND6_WIDESCREEN,
	&IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN,
	&IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN,
	&IMAGE_AQUARIUM1_WIDESCREEN,
	&IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN,
	&IMAGE_ALMANAC_INDEXBACK_WIDESCREEN,
	&IMAGE_ALMANAC_PLANTBACK_WIDESCREEN,
	&IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN,
	&IMAGE_ZOMBATAR_BG_WIDESCREEN,
	&IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN,
	&IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN,
	&IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN,
	&IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN,
	&IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN,
	&IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN,
	&IMAGE_REANIM_TREE_BG_WIDESCREEN,
	&IMAGE_BACKGROUND1_COVER,
	&IMAGE_BACKGROUND2_COVER,
	&IMAGE_BACKGROUND3_COVER,
	&IMAGE_BACKGROUND4_COVER,
	&IMAGE_BACKGROUND5_TREES,
	&IMAGE_BACKGROUND5_POLE,
	&IMAGE_BACKGROUND6_TREES,
	&IMAGE_BACKGROUND6_POLE,
#endif
	nullptr
};

Image* Sexy::ResoddedFrameworkLoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(ResoddedFrameworkGetStringIdById(theId)));
}

void Sexy::ResoddedFrameworkReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(ResoddedFrameworkGetStringIdById(theId),theImage);
	 * (Image**)gResources[theId] = theImage; 
}

Image* Sexy::ResoddedFrameworkGetImageById(int theId)
{
	if (theId < 0 || theId >= ResoddedFrameworkRESOURCE_ID_MAX)
		return nullptr;
	return *(Image**)gResources[theId];
}

Font* Sexy::ResoddedFrameworkGetFontById(int theId)
{
	if (theId < 0 || theId >= ResoddedFrameworkRESOURCE_ID_MAX)
		return nullptr;
	return *(Font**)gResources[theId];
}

int Sexy::ResoddedFrameworkGetSoundById(int theId)
{
	if (theId < 0 || theId >= ResoddedFrameworkRESOURCE_ID_MAX)
		return -1;
	return *(int*)gResources[theId];
}

Image*& Sexy::ResoddedFrameworkGetImageRefById(int theId)
{
	static Image* aNullImage = nullptr;
	if (theId < 0 || theId >= ResoddedFrameworkRESOURCE_ID_MAX)
		return aNullImage;
	return *(Image**)gResources[theId];
}

Font*& Sexy::ResoddedFrameworkGetFontRefById(int theId)
{
	static Font* aNullFont = nullptr;
	if (theId < 0 || theId >= ResoddedFrameworkRESOURCE_ID_MAX)
		return aNullFont;
	return *(Font**)gResources[theId];
}

int& Sexy::ResoddedFrameworkGetSoundRefById(int theId)
{
	static int aNullSound = -1;
	if (theId < 0 || theId >= ResoddedFrameworkRESOURCE_ID_MAX)
		return aNullSound;
	return *(int*)gResources[theId];
}

static Sexy::ResoddedFrameworkResourceId ResoddedFrameworkGetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<ResoddedFrameworkRESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return ResoddedFrameworkRESOURCE_ID_MAX;
	else
		return (ResoddedFrameworkResourceId) anItr->second;
}

Sexy::ResoddedFrameworkResourceId Sexy::ResoddedFrameworkGetIdByImage(Image *theImage)
{
	return ResoddedFrameworkGetIdByVariable(theImage);
}

Sexy::ResoddedFrameworkResourceId Sexy::ResoddedFrameworkGetIdByFont(Font *theFont)
{
	return ResoddedFrameworkGetIdByVariable(theFont);
}

Sexy::ResoddedFrameworkResourceId Sexy::ResoddedFrameworkGetIdBySound(int theSound)
{
	return ResoddedFrameworkGetIdByVariable((void*)theSound);
}

const char* Sexy::ResoddedFrameworkGetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_SEED_SELECTOR_ID: return "IMAGE_SEED_SELECTOR";
		case IMAGE_GAMEPAD_CURSOR_FRAME_ID: return "IMAGE_GAMEPAD_CURSOR_FRAME";
		case IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW_ID: return "IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW";
            case IMAGE_GAMEPAD_SELECTOR_SHADOW_ID: return "IMAGE_GAMEPAD_SELECTOR_SHADOW";
			case IMAGE_GAMEPAD_ARROW_ID: return "IMAGE_GAMEPAD_ARROW";
		case IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW_ID: return "IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW";
#if LAWN_WIDESCREEN
		case IMAGE_TITLESCREEN_WIDESCREEN_ID: return "IMAGE_TITLESCREEN_WIDESCREEN";
		case IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN_ID: return "IMAGE_ACHEESEMENTS_CHINA_WIDESCREEN";
		case IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN_ID: return "IMAGE_ACHEESEMENTS_HOLE_TILE_WIDESCREEN";
		case IMAGE_STORE_BACKGROUND_WIDESCREEN_ID: return "IMAGE_STORE_BACKGROUND_WIDESCREEN";
		case IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN_ID: return "IMAGE_STORE_BACKGROUNDNIGHT_WIDESCREEN";
		case IMAGE_STORE_CAR_WIDESCREEN_ID: return "IMAGE_STORE_CAR_WIDESCREEN";
		case IMAGE_STORE_CAR_NIGHT_WIDESCREEN_ID: return "IMAGE_STORE_CAR_NIGHT_WIDESCREEN";
		case IMAGE_STORE_CARCLOSED_WIDESCREEN_ID: return "IMAGE_STORE_CARCLOSED_WIDESCREEN";
		case IMAGE_STORE_CARCLOSED_NIGHT_WIDESCREEN_ID: return "IMAGE_STORE_CARCLOSED_NIGHT_WIDESCREEN";
		case IMAGE_STORE_HATCHBACKOPEN_WIDESCREEN_ID: return "IMAGE_STORE_HATCHBACKOPEN_WIDESCREEN";
		case IMAGE_STORE_SIGN_WIDESCREEN_ID: return "IMAGE_STORE_SIGN_WIDESCREEN";
		case IMAGE_STORE_MAINMENUBUTTON_WIDESCREEN_ID: return "IMAGE_STORE_MAINMENUBUTTON_WIDESCREEN";
		case IMAGE_STORE_MAINMENUBUTTONDOWN_WIDESCREEN_ID: return "IMAGE_STORE_MAINMENUBUTTONDOWN_WIDESCREEN";
		case IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_WIDESCREEN_ID: return "IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_WIDESCREEN";
		case IMAGE_STORE_PREVBUTTON_WIDESCREEN_ID: return "IMAGE_STORE_PREVBUTTON_WIDESCREEN";
		case IMAGE_STORE_PREVBUTTONHIGHLIGHT_WIDESCREEN_ID: return "IMAGE_STORE_PREVBUTTONHIGHLIGHT_WIDESCREEN";
		case IMAGE_STORE_PREVBUTTONDISABLED_WIDESCREEN_ID: return "IMAGE_STORE_PREVBUTTONDISABLED_WIDESCREEN";
		case IMAGE_STORE_NEXTBUTTON_WIDESCREEN_ID: return "IMAGE_STORE_NEXTBUTTON_WIDESCREEN";
		case IMAGE_STORE_NEXTBUTTONHIGHLIGHT_WIDESCREEN_ID: return "IMAGE_STORE_NEXTBUTTONHIGHLIGHT_WIDESCREEN";
		case IMAGE_STORE_NEXTBUTTONDISABLED_WIDESCREEN_ID: return "IMAGE_STORE_NEXTBUTTONDISABLED_WIDESCREEN";
		case IMAGE_BACKGROUND1_WIDESCREEN_ID: return "IMAGE_BACKGROUND1_WIDESCREEN";
		case IMAGE_BACKGROUND2_WIDESCREEN_ID: return "IMAGE_BACKGROUND2_WIDESCREEN";
		case IMAGE_BACKGROUND3_WIDESCREEN_ID: return "IMAGE_BACKGROUND3_WIDESCREEN";
		case IMAGE_BACKGROUND4_WIDESCREEN_ID: return "IMAGE_BACKGROUND4_WIDESCREEN";
		case IMAGE_BACKGROUND5_WIDESCREEN_ID: return "IMAGE_BACKGROUND5_WIDESCREEN";
		case IMAGE_BACKGROUND6_WIDESCREEN_ID: return "IMAGE_BACKGROUND6_WIDESCREEN";
		case IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN_ID: return "IMAGE_BACKGROUND_GREENHOUSE_WIDESCREEN";
		case IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN_ID: return "IMAGE_BACKGROUND_MUSHROOMGARDEN_WIDESCREEN";
		case IMAGE_AQUARIUM1_WIDESCREEN_ID: return "IMAGE_AQUARIUM1_WIDESCREEN";
		case IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN_ID: return "IMAGE_CHALLENGE_BACKGROUND_WIDESCREEN";
		case IMAGE_ALMANAC_INDEXBACK_WIDESCREEN_ID: return "IMAGE_ALMANAC_INDEXBACK_WIDESCREEN";
		case IMAGE_ALMANAC_PLANTBACK_WIDESCREEN_ID: return "IMAGE_ALMANAC_PLANTBACK_WIDESCREEN";
		case IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN_ID: return "IMAGE_ALMANAC_ZOMBIEBACK_WIDESCREEN";
		case IMAGE_ZOMBATAR_BG_WIDESCREEN_ID: return "IMAGE_ZOMBATAR_BG_WIDESCREEN";
		case IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN_ID: return "IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_WIDESCREEN";
		case IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN_ID: return "IMAGE_REANIM_SELECTORSCREEN_BG_LEFT_WIDESCREEN";
		case IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN_ID: return "IMAGE_REANIM_SELECTORSCREEN_BG_CENTER_WIDESCREEN";
		case IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN_ID: return "IMAGE_REANIM_SELECTORSCREEN_BG_RIGHT_WIDESCREEN";
		case IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN_ID: return "IMAGE_REANIM_SELECTORSCREEN_BG_WIDESCREEN";
		case IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN_ID: return "IMAGE_REANIM_SELECTORSCREEN_WOODSIGN1_WIDESCREEN";
		case IMAGE_REANIM_TREE_BG_WIDESCREEN_ID: return "IMAGE_REANIM_TREE_BG_WIDESCREEN";
		case IMAGE_BACKGROUND1_COVER_ID: return "IMAGE_BACKGROUND1_COVER";
		case IMAGE_BACKGROUND2_COVER_ID: return "IMAGE_BACKGROUND2_COVER";
		case IMAGE_BACKGROUND3_COVER_ID: return "IMAGE_BACKGROUND3_COVER";
		case IMAGE_BACKGROUND4_COVER_ID: return "IMAGE_BACKGROUND4_COVER";
		case IMAGE_BACKGROUND5_TREES_ID: return "IMAGE_BACKGROUND5_TREES";
		case IMAGE_BACKGROUND5_POLE_ID: return "IMAGE_BACKGROUND5_POLE";
		case IMAGE_BACKGROUND6_TREES_ID: return "IMAGE_BACKGROUND6_TREES";
		case IMAGE_BACKGROUND6_POLE_ID: return "IMAGE_BACKGROUND6_POLE";
#endif
		default: return "";
	}
}


